name: deploy workflow
run-name: ${{ gitea.actor }} is deploying the website
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun run build
      - run: bun netlify deploy --prod
